// Generated by `pnpm gen:chains`
export {
  arbitrum,
  arbitrumSepolia,
  base,
  baseSepolia,
  berachain,
  bsc,
  celo,
  hoodi,
  katana,
  mainnet,
  optimism,
  optimismSepolia,
  polygon,
  sepolia,
} from 'viem/chains'