/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ThemeSwitchImport } from './routes/ThemeSwitch'
import { Route as SpinnerImport } from './routes/Spinner'
import { Route as SpacerImport } from './routes/Spacer'
import { Route as SeparatorImport } from './routes/Separator'
import { Route as ScreenImport } from './routes/Screen'
import { Route as InputImport } from './routes/Input'
import { Route as FrameImport } from './routes/Frame'
import { Route as ColorsImport } from './routes/Colors'
import { Route as ButtonAreaImport } from './routes/ButtonArea'
import { Route as ButtonImport } from './routes/Button'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ThemeSwitchRoute = ThemeSwitchImport.update({
  id: '/ThemeSwitch',
  path: '/ThemeSwitch',
  getParentRoute: () => rootRoute,
} as any)

const SpinnerRoute = SpinnerImport.update({
  id: '/Spinner',
  path: '/Spinner',
  getParentRoute: () => rootRoute,
} as any)

const SpacerRoute = SpacerImport.update({
  id: '/Spacer',
  path: '/Spacer',
  getParentRoute: () => rootRoute,
} as any)

const SeparatorRoute = SeparatorImport.update({
  id: '/Separator',
  path: '/Separator',
  getParentRoute: () => rootRoute,
} as any)

const ScreenRoute = ScreenImport.update({
  id: '/Screen',
  path: '/Screen',
  getParentRoute: () => rootRoute,
} as any)

const InputRoute = InputImport.update({
  id: '/Input',
  path: '/Input',
  getParentRoute: () => rootRoute,
} as any)

const FrameRoute = FrameImport.update({
  id: '/Frame',
  path: '/Frame',
  getParentRoute: () => rootRoute,
} as any)

const ColorsRoute = ColorsImport.update({
  id: '/Colors',
  path: '/Colors',
  getParentRoute: () => rootRoute,
} as any)

const ButtonAreaRoute = ButtonAreaImport.update({
  id: '/ButtonArea',
  path: '/ButtonArea',
  getParentRoute: () => rootRoute,
} as any)

const ButtonRoute = ButtonImport.update({
  id: '/Button',
  path: '/Button',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Button': {
      id: '/Button'
      path: '/Button'
      fullPath: '/Button'
      preLoaderRoute: typeof ButtonImport
      parentRoute: typeof rootRoute
    }
    '/ButtonArea': {
      id: '/ButtonArea'
      path: '/ButtonArea'
      fullPath: '/ButtonArea'
      preLoaderRoute: typeof ButtonAreaImport
      parentRoute: typeof rootRoute
    }
    '/Colors': {
      id: '/Colors'
      path: '/Colors'
      fullPath: '/Colors'
      preLoaderRoute: typeof ColorsImport
      parentRoute: typeof rootRoute
    }
    '/Frame': {
      id: '/Frame'
      path: '/Frame'
      fullPath: '/Frame'
      preLoaderRoute: typeof FrameImport
      parentRoute: typeof rootRoute
    }
    '/Input': {
      id: '/Input'
      path: '/Input'
      fullPath: '/Input'
      preLoaderRoute: typeof InputImport
      parentRoute: typeof rootRoute
    }
    '/Screen': {
      id: '/Screen'
      path: '/Screen'
      fullPath: '/Screen'
      preLoaderRoute: typeof ScreenImport
      parentRoute: typeof rootRoute
    }
    '/Separator': {
      id: '/Separator'
      path: '/Separator'
      fullPath: '/Separator'
      preLoaderRoute: typeof SeparatorImport
      parentRoute: typeof rootRoute
    }
    '/Spacer': {
      id: '/Spacer'
      path: '/Spacer'
      fullPath: '/Spacer'
      preLoaderRoute: typeof SpacerImport
      parentRoute: typeof rootRoute
    }
    '/Spinner': {
      id: '/Spinner'
      path: '/Spinner'
      fullPath: '/Spinner'
      preLoaderRoute: typeof SpinnerImport
      parentRoute: typeof rootRoute
    }
    '/ThemeSwitch': {
      id: '/ThemeSwitch'
      path: '/ThemeSwitch'
      fullPath: '/ThemeSwitch'
      preLoaderRoute: typeof ThemeSwitchImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Button': typeof ButtonRoute
  '/ButtonArea': typeof ButtonAreaRoute
  '/Colors': typeof ColorsRoute
  '/Frame': typeof FrameRoute
  '/Input': typeof InputRoute
  '/Screen': typeof ScreenRoute
  '/Separator': typeof SeparatorRoute
  '/Spacer': typeof SpacerRoute
  '/Spinner': typeof SpinnerRoute
  '/ThemeSwitch': typeof ThemeSwitchRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Button': typeof ButtonRoute
  '/ButtonArea': typeof ButtonAreaRoute
  '/Colors': typeof ColorsRoute
  '/Frame': typeof FrameRoute
  '/Input': typeof InputRoute
  '/Screen': typeof ScreenRoute
  '/Separator': typeof SeparatorRoute
  '/Spacer': typeof SpacerRoute
  '/Spinner': typeof SpinnerRoute
  '/ThemeSwitch': typeof ThemeSwitchRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/Button': typeof ButtonRoute
  '/ButtonArea': typeof ButtonAreaRoute
  '/Colors': typeof ColorsRoute
  '/Frame': typeof FrameRoute
  '/Input': typeof InputRoute
  '/Screen': typeof ScreenRoute
  '/Separator': typeof SeparatorRoute
  '/Spacer': typeof SpacerRoute
  '/Spinner': typeof SpinnerRoute
  '/ThemeSwitch': typeof ThemeSwitchRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Button'
    | '/ButtonArea'
    | '/Colors'
    | '/Frame'
    | '/Input'
    | '/Screen'
    | '/Separator'
    | '/Spacer'
    | '/Spinner'
    | '/ThemeSwitch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Button'
    | '/ButtonArea'
    | '/Colors'
    | '/Frame'
    | '/Input'
    | '/Screen'
    | '/Separator'
    | '/Spacer'
    | '/Spinner'
    | '/ThemeSwitch'
  id:
    | '__root__'
    | '/'
    | '/Button'
    | '/ButtonArea'
    | '/Colors'
    | '/Frame'
    | '/Input'
    | '/Screen'
    | '/Separator'
    | '/Spacer'
    | '/Spinner'
    | '/ThemeSwitch'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ButtonRoute: typeof ButtonRoute
  ButtonAreaRoute: typeof ButtonAreaRoute
  ColorsRoute: typeof ColorsRoute
  FrameRoute: typeof FrameRoute
  InputRoute: typeof InputRoute
  ScreenRoute: typeof ScreenRoute
  SeparatorRoute: typeof SeparatorRoute
  SpacerRoute: typeof SpacerRoute
  SpinnerRoute: typeof SpinnerRoute
  ThemeSwitchRoute: typeof ThemeSwitchRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ButtonRoute: ButtonRoute,
  ButtonAreaRoute: ButtonAreaRoute,
  ColorsRoute: ColorsRoute,
  FrameRoute: FrameRoute,
  InputRoute: InputRoute,
  ScreenRoute: ScreenRoute,
  SeparatorRoute: SeparatorRoute,
  SpacerRoute: SpacerRoute,
  SpinnerRoute: SpinnerRoute,
  ThemeSwitchRoute: ThemeSwitchRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Button",
        "/ButtonArea",
        "/Colors",
        "/Frame",
        "/Input",
        "/Screen",
        "/Separator",
        "/Spacer",
        "/Spinner",
        "/ThemeSwitch"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/Button": {
      "filePath": "Button.tsx"
    },
    "/ButtonArea": {
      "filePath": "ButtonArea.tsx"
    },
    "/Colors": {
      "filePath": "Colors.tsx"
    },
    "/Frame": {
      "filePath": "Frame.tsx"
    },
    "/Input": {
      "filePath": "Input.tsx"
    },
    "/Screen": {
      "filePath": "Screen.tsx"
    },
    "/Separator": {
      "filePath": "Separator.tsx"
    },
    "/Spacer": {
      "filePath": "Spacer.tsx"
    },
    "/Spinner": {
      "filePath": "Spinner.tsx"
    },
    "/ThemeSwitch": {
      "filePath": "ThemeSwitch.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
