import { defineChain } from 'viem'
import { anvil } from 'viem/chains'

export type { Chain } from 'viem/chains'
// Generated by `scripts/chains.ts`
export {
  anvil,
  base,
  baseSepolia,
  optimismSepolia,
} from 'viem/chains'

/** Additional Anvil environment, purposed for interop. */
export const anvil2 = /*#__PURE__*/ defineChain({
  ...anvil,
  id: 31_338,
})

/** Additional Anvil environment, purposed for interop. */
export const anvil3 = /*#__PURE__*/ defineChain({
  ...anvil,
  id: 31_339,
})
